{% set name = "netsuitesdk" %}
{% set version = "2.21.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/netsuitesdk-{{ version }}.tar.gz
  sha256: bd66f65ef91298eca39968f01a72dee082223126758618fed60d129b6164b66e

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=2.5
  run:
    - python >=2.5
    - zeep

test:
  imports:
    - netsuitesdk
    - netsuitesdk.api
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/fylein/netsuite-sdk-py
  summary: Python SDK for accessing the NetSuite SOAP webservice
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - conda-forge/rpaframework-core
