{% set name = "netsuitesdk" %}
{% set version = "2.1.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/netsuitesdk-{{ version }}.tar.gz
  sha256: 1e2cb51e7195e4ae89fadeb05b26a7b15de9d22b3e57e816b5116d7685dd2cb7

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=2.5
  run:
    - python >=2.5
    - zeep

test:
  imports:
    - netsuitesdk
    - netsuitesdk.api
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/fylein/netsuite-sdk-py
  summary: Python SDK for accessing the NetSuite SOAP webservice
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - conda-forge/rpaframework-core
