{% set name = "netsuitesdk" %}
{% set version = "2.17.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/netsuitesdk-{{ version }}.tar.gz
  sha256: 4b2f9b087fc50e826af0cc04f60ad97c1237631c04dce8d1f6470c72910e9304

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=2.5
  run:
    - python >=2.5
    - zeep

test:
  imports:
    - netsuitesdk
    - netsuitesdk.api
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/fylein/netsuite-sdk-py
  summary: Python SDK for accessing the NetSuite SOAP webservice
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - conda-forge/rpaframework-core
