{% set name = "netsuitesdk" %}
{% set version = "2.0.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/netsuitesdk-{{ version }}.tar.gz
  sha256: f908a3782ce878828f620637100698f58f546302e6b5b7e1819b47227182a35d

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=2.5
  run:
    - python >=2.5
    - zeep

test:
  imports:
    - netsuitesdk
    - netsuitesdk.api
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/fylein/netsuite-sdk-py
  summary: Python SDK for accessing the NetSuite SOAP webservice
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - conda-forge/rpaframework-core
