{% set name = "netsuitesdk" %}
{% set version = "2.21.4" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/netsuitesdk-{{ version }}.tar.gz
  sha256: c70d78e4e337515e8a350b7db86db17795dc40feaf563963e7f28f87f6a3fec9

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=2.5
  run:
    - python >=2.5
    - zeep

test:
  imports:
    - netsuitesdk
    - netsuitesdk.api
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/fylein/netsuite-sdk-py
  summary: Python SDK for accessing the NetSuite SOAP webservice
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - conda-forge/rpaframework-core
